### ISSUE TITLE
System.NullReferenceException: "RapidApi key not found"

### ISSUE THREAD

**Issue by karmat75** [LazZiya/XLocalizer.Translate.MicrosoftTranslate#1]
Hello LazZiya,

thank you at first for this very nice peace of code. It will help save so much time in my live!

When i use the Microsoft Translation Service, without RapidAPI, it throws a NullReferenceException with the Message "RapidApi key not found." In my StackTrace i can folow this error up to the DI for the Logger inside the Class XLocalizer.Translate.MicrosoftTranslate.

How can i use the MS Translate API without the RapidAPI?

https://github.com/LazZiya/XLocalizer.Translate.MicrosoftTranslate/blob/2a5ec2e3f90b9bfeea6718db7196268037531d3a/XLocalizer.Translate.MicrosoftTranslate/MicrosoftTranslateService.cs#L33

**Comment by karmat75** [comment]
I solved the issue for me.
The Problem was, i changed the Environment  but i forgot to fill all needed information into the corosponding appsetting.json.

Maybe it will be possible to etablish a more specific error message for cases like:
- Config not found/set
- Using Microsoft Translate direct and over RapidAPI

Thank you for your time!

Best Regards

**Comment by LazZiya** [comment]
Hi @MatthiasKargel , thank you for your kind message and for raising this issue :)

You are right, I will publish a hotfix soon.

**Comment by LazZiya** [comment]
Fixed with dd3b1f2
New release v1.0.1 is availavle to download from nuget.

Best regards,
Ziya
